djangodelight/urls.py
from django.contrib import admin
from django.urls import path, include
from inventory import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path("", views.home, name = "home"),
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(), name="login"),
    path("logout/", views.logout_view,name = "logout" ),
    path("ingredient/list", views.IngredientList.as_view(), name = "ingredientlist"),
    path("ingredient/delete/<pk>", views.IngredientDelete.as_view(), name = "ingredientdelete"),
    path("purchase/list", views.PurchasesList.as_view(), name = "purchaseslist"),
    path("menuitem/list", views.MenuItemList.as_view(), name = "menuitemlist"),
    path("purchase/create", views.CreateViewPurchase.as_view(), name = "createpurchase"),
    path("ingredient/create", views.CreateViewIngredient.as_view(), name = "createingredient"),
    path("menuitem/create", views.CreateViewMenu.as_view(), name = "createmenuitem"),
    path("ingredient/<pk>/update", views.UpdateViewIngredient.as_view(), name = "updateingredient")
    
]

inventory/models.py
from statistics import quantiles
from tkinter import CASCADE
from zoneinfo import available_timezones
from django.db import models
# Create your models here.
class Ingredient(models.Model):
    name = models.CharField(max_length=100)
    quantity = models.FloatField(default=1)
    unit = models.CharField(max_length= 100)
    unit_price = models.FloatField(default = 0.00)

    def __str__(self):
        return "Ingredient = {}, Availability = {}, Unit = {}, price per unit = {}".format(self.name, self.quantity, self.unit, self.unit_price)
    

    def get_absolute_url(self):
        return "list"


class MenuItems(models.Model):
    title = models.CharField(max_length= 100)
    price = models.FloatField(default= 0.00)

    def __str__(self):
        return f"Item = {self.title}, Item Price = {self.price}"
    
    def get_absolute_url(self):
        return "list"

class RecipeRequirement(models.Model):
    menu_item = models.ForeignKey(MenuItems, on_delete = models.CASCADE)
    ingredient = models.ForeignKey(Ingredient,  on_delete = models.CASCADE)
    quantity = models.FloatField(default= 0)

    def __str__(self):
        return f"Menu Item = [{self.menu_item.__str__()}], Ingredient Item = {self.ingredient}, Quantity = {self.quantity}"
class Purchases(models.Model):
    menu_item = models.ForeignKey( MenuItems, on_delete =models.CASCADE)
    timestamp = models.DateField(auto_now = True)

    def __str__(self):
        return f"Menu item = [{self.menu_item.__str__()}], Time Stamp = {self.timestamp}"
    

    def get_absolute_url(self):
        return "list"

inventory/forms.py
from ast import In
from dataclasses import fields
from re import purge
from django import forms
from .models import Ingredient, Purchases, MenuItems, RecipeRequirement

class CreateMenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItems
        fields = "__all__"

class CreateIngredientItemForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = "__all__"

class UpdateRecipeRequirementForm(forms.ModelForm):
    class Meta:
        model = RecipeRequirement
        fields = "__all__"

class CreatePurchaseForm(forms.ModelForm):
    class Meta:
        model = Purchases
        fields = "__all__"


class UpdateIngredientForm(forms.ModelForm):
    class Meta:
        model =Ingredient
        fields = "__all__"

inventory/views.py
from dataclasses import fields
from re import template
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import MenuItems, Ingredient, RecipeRequirement, Purchases
from .forms import CreatePurchaseForm, CreateIngredientItemForm, CreateMenuItemForm, UpdateIngredientForm
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

# Create your views here.
def home(request):
    queryset = Ingredient.objects.all()
    queryset1 = Purchases.objects.all()
    queryset2 = MenuItems.objects.all()
    context = {
        'ingredient_list': queryset,
        'purchases_list' : queryset1,
        'menu_list' : queryset2
    }
    return render(request, "inventory/home.html", context)




class MenuItemList(LoginRequiredMixin,ListView):
    model = MenuItems
    template_name = "menu_list.html"

class IngredientList(LoginRequiredMixin, ListView):
    model = Ingredient
    template_name = "ingredient_list.html"

    # def post(self, request, *args, **kwargs):
    #     return UpdateIngredientForm(request) # W


# class RecipeRequirementList(ListView):
#     model = RecipeRequirement
#     template_name = ""

class PurchasesList(LoginRequiredMixin, ListView):
    model = Purchases
    template_name = "purchases_list_html"

class IngredientDelete(LoginRequiredMixin, DeleteView):
    model = Ingredient
    template_name = ""
    fields = ["name", "quantity","unit","unit_price"]

# class PurchasesDelete(DeleteView):
#     model = Purchases
#     template_name = ""
#     fields = ["menu_item", "timestamp"]


class CreateViewPurchase(LoginRequiredMixin, CreateView):
    model = Purchases
    template_name = "inventory/add_purchase.html"
    form_class = CreatePurchaseForm


class CreateViewIngredient(LoginRequiredMixin, CreateView):
    model = Ingredient
    template_name = "inventory/add_ingredient.html"
    form_class = CreateIngredientItemForm


class CreateViewMenu(LoginRequiredMixin, CreateView):
    model = MenuItems
    template_name = "inventory/add_menu_item.html"
    form_class = CreateMenuItemForm


class UpdateViewIngredient(LoginRequiredMixin, UpdateView):
    model = Ingredient
    template_name = "inventory/update_ingredient.html"
    form_class = UpdateIngredientForm
    success_url = reverse_lazy('ingredientlist')


    # def get_success_url(self) -> str:
    #     return reverse_lazy('ingredientlist')



def logout_view(request):
    logout(request)
    return redirect("home")

inventory/templates/base.html
{% load static %} 
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="{% static 'inventory/style.css' %}" />
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap" rel="stylesheet">
  <title>{% block title %}Django Delights{% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
  <div class="app">
  <header>
    <div class="header-first-row">
      <h1 class="title">Django Delights</h1>
      
      <a class="logout" href="{% url 'logout' %}">Logout</a>
      
    </div>
      <nav class="navbar">
        <a class="nav-item{% if request.path == home_url %} current-page{% endif %}" href="{% url 'home' %}">Home</a>
        <a class="nav-item{% if request.path == ingredients_url %} current-page{% endif %}" href="{% url 'ingredientlist' %}">Ingredients</a>
        <a class="nav-item{% if request.path == menu_url %} current-page{% endif %}" href="{% url 'menuitemlist' %}">Menu</a>
        <a class="nav-item{% if request.path == purchases_url %} current-page{% endif %}" href="{% url 'purchaseslist' %}">Purchases</a>
      </nav>
    
  </header>
  <main>
    {% block content %}{% endblock %}
  </main>
  </div>
</body>
</html>

inventory/templates/inventory/add_ingredient.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Ingredient to Inventory</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

inventory/templates/inventory/add_menu_item.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Item to Menu</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

inventory/templates/inventory/add_purchase.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Enter a new purchase</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

inventory/templates/inventory/add_recipe_requirement.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Recipe Requirement for a Menu Item</h2>
    <form method="post">
    <div>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </div>
    </form>
{% endblock %}

inventory/templates/inventory/home.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block content %}
    <div class="home">
        <div>
            <h2>Ingredients</h2>
            <table class="inventory-table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Unit</th>
                        <th>Unit Price</th>
                    </tr>
                </thead>
                <tbody>
                {% for ingredient in ingredient_list %}
                    <tr>
                        <td>{{ ingredient.name }}</td>
                        <td>{{ ingredient.quantity }}</td>
                        <td>{{ ingredient.unit }}</td>
                        <td class="price">${{ ingredient.unit_price|stringformat:".2f" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <hr/>

        <div>
            <h2>Purchases</h2>
            <table class="inventory-table">
                <thead>
                    <tr>
                        <th>Menu Item</th>
                        <th>Price</th>
                        <th>Time</th>
                    </tr>
                </thead>
                <tbody>
                {% for purchase in purchases_list %}
                    <tr>
                        <td>{{ purchase.menu_item.title }}</td>
                        <td class="price">${{ purchase.menu_item.price|stringformat:".2f" }}</td>
                        <td>{{ purchase.timestamp }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <hr/>

        <div>
            <h2>Menu</h2>
            <ul class="menu-items">
            {% for menu_item in menu_list %}
                <li>
                    <div class="menu-item-header">
                        <div class="menu-item-title">{{ menu_item.title }}</div>
                        <div class="menu-item-price">${{ menu_item.price|stringformat:".2f" }}</div>
                    </div>
                    <ul class="menu-item-ingredients">
                        {% for recipe_requirement in menu_item.reciperequirement_set.all %}
                        <li>{{ recipe_requirement.quantity }} {{recipe_requirement.ingredient.unit }} {{ recipe_requirement.ingredient.name }}</li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

inventory/templates/inventory/ingredient_list.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Add Ingredient to Inventory</h2>
    <div>
        <h2>Ingredients</h2>
        <a href = "{% url 'createingredient' %}">Add Ingredients</a>
        <table class="inventory-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Quantity</th>
                    <th>Unit</th>
                    <th>Unit Price</th>
                </tr>
            </thead>
            <tbody>
            {% for ingredient in ingredient_list %}
                <tr>
                    <td>{{ ingredient.name }}</td>
                    <td>{{ ingredient.quantity }}</td>
                    <td>{{ ingredient.unit }}</td>
                    <td class="price">${{ ingredient.unit_price|stringformat:".2f" }}</td>
                    <td><a href="{% url 'updateingredient' ingredient.id %}"><button>Update</button></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

inventory/templates/inventory/menuitems_list.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Delights{% endblock %}
{% block head %}
{% endblock %}
{% block content %}
    <h2>Menu Items<h2>
    <a href = "{% url 'createmenuitem' %}">Add Menu Item</a>
    <a href = "{% url 'createmenuitem' %}">Add Menu Item</a>
    <hr/>
    <ul>
    {% for menu_item in menuitems_list %}
    <li>
        <div>
            <div>{{ menu_item.title }}</div>
            <div class="menu-item-price">${{ menu_item.price|stringformat:".2f" }}</div>
        </div>
    </li>

    {% endfor %}
    </ul>
{% endblock %}

inventory/templates/inventory/purchases_list.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
{% endblock %}
{% block content %}
    <h2>Purchases</h2>
    <a href = "{% url 'createpurchase' %}">Add Purchases</a>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Menu Item</th>
                <th>Price</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in purchases_list %}
            <tr>
                <td>{{ purchase.menu_item.title }}</td>
                <td class="price">${{ purchase.menu_item.price|stringformat:".2f" }}</td>
                <td>{{ purchase.timestamp }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

inventory/templates/inventory/reports.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
{% endblock %}
{% block content %}
    <h2>Purchases</h2>
    <table class="inventory-table">
        <thead>
            <tr>
                <th>Menu Item</th>
                <th>Price</th>
                <th>Time</th>
            </tr>
        </thead>
        <tbody>
        {% for purchase in purchases %}
            <tr>
                <td>{{ purchase.menu_item.title }}</td>
                <td class="price">${{ purchase.menu_item.price|stringformat:".2f" }}</td>
                <td>{{ purchase.timestamp }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <hr/>
    <h2>Totals</h2>
    <div style="color: green;">Total Revenue: ${{ revenue|stringformat:".2f" }}</div>
    <div style="color: red;">Total Cost: ${{ total_cost|stringformat:".2f" }}</div>
    <div style="color: blue;">Total Profit: ${{ profit|stringformat:".2f" }}</div>
{% endblock %}

inventory/templates/inventory/update_ingredient.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}
    <h2>Update Ingredient in Inventory</h2>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update"/>
    </form>
{% endblock %}